[workspace]
members = [
  "dns",
  "get_fw_version",
  "join",
  "send_data_tcp",
  "receive_data_tcp"
]

[profile.dev]
codegen-units = 1
incremental = false
lto = 'fat'
opt-level = 's'

[profile.test]
codegen-units = 1
incremental = false
lto = 'fat'
opt-level = 's'