name: Bug Report
description: File a bug report for esp32-wroom-rp
title: "[Bug]: "
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue here.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: hardware
    attributes:
      label: What is the exact model of RP2040 hardware you are seeing the problem on?
      placeholder: ex. Raspberry Pi Pico, Adafruit Feather RP2040, etc.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Any related code to produce this issue.
      description: Please copy and paste any relevant code to re-produce this issue. If you have your own public repository, you can link to that here. 
      render: shell
