name: Build & Test Crate + Examples

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install latest rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: thumbv6m-none-eabi
        default: true
        override: true
    - name: Build crate
      run: cargo build --verbose
    - name: Install supporting crates
      run: cargo install flip-link
    - name: Run tests
      run: cargo test --verbose
    # Now build debug and release versions of all example target applications
    - name: Build debug examples
      run: cd cross && cargo build --verbose
    - name: Build release examples
      run: cd cross && cargo build --verbose --release
