name: Build & Test Crate + Examples

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build crate
      run: cargo build --verbose
    - name: Build debug examples
      run: cargo build --verbose --examples
    #- run: echo "Debug examples built:" && ls target/thumbv6m-none-eabi/debug/examples/ |grep -v '-' |grep -v '\.d'
    #- run: rm target/thumbv6m-none-eabi/debug/examples/ -rf
    - name: Build release examples
      run: cargo build --verbose --release --examples
    #- run: echo "Release examples built:" && ls target/thumbv6m-none-eabi/release/examples/ |grep -v '-' |grep -v '\.d'
    #- run: rm target/thumbv6m-none-eabi/release/examples/ -rf
    - name: Run tests
      run: cargo test --verbose
