name: Build & Test Crate + Examples

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: thumbv6m-none-eabi
        override: true
        profile: minimal
    - name: Build
      run: cargo build --verbose
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --examples
    - run: echo "Debug examples built:" && ls target/thumbv6m-none-eabi/debug/examples/ |grep -v '-' |grep -v '\.d'
    - run: rm target/thumbv6m-none-eabi/debug/examples/ -rf
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --examples
    - run: echo "Release examples built:" && ls target/thumbv6m-none-eabi/release/examples/ |grep -v '-' |grep -v '\.d'
    - run: rm target/thumbv6m-none-eabi/release/examples/ -rf
    - name: Run tests
      run: cargo test --verbose
